---
title: "STAT 441/541 Project"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Project Overview
The first experimental design project will be due on March 30th. Together the two projects compose 30% of your final grade. The first project should be a fairly simple experimental design with a single treatment factor. 

The submission will consist of two components: an experimental plan and a project summary. All written documents will be completed through R Markdown to enable reproducibility.


### Checkpoints

There have been several checkpoints to scaffold the submission

- February 9: Project Proposal 1 (Quiz 3)
- February 23: Project Proposal 2 (Quiz 5)
- March 2: Pilot Study (Quiz 6)
- March 9: Sample Size Calculations (Quiz 7)
- March 23: Complete Experimental Design plan (HW 8)

#### Experimental Design Plan

The experimental design should address the following 10 points

1. Define objectives
2. Define meaningful and measurable response
3. Diagram treatment application process for a single run
4. Identify experimental units
5. List sources of variation
6. Perform pilot runs
7. Choose experimental design (i.e. randomization)
8. Determine number of replicates required
9. Describe method(s) for data analysis
10. Timetable and budget for resources to complete experiment

Bullet points and short answer are acceptable. This should help inform your written project summary.


#### Written Project Summary

The written project summary should contain complete sentences and paragraphs. Please follow the suggested structure for the project summary.

1. __Introduction__: define research object and state why it is important, interesting, or useful
2. __Experimental Units and Randomization:__ items 2 - 5 + 7. Describe experimental units and how responses will be measured. Discuss additional sources of variation and how they were controlled for or, alternatively, how they may impact results. Finally, detail the treatment assignment procedure. You are welcome to embed code.
3. __Pilot Study and Sample Size Calculations:__ Summarize what you learned from your pilot study. Include sample size calculations - specify and defend your assumptions and choices. Again - it is okay if you cannot achieve the desired sample 
4. __Data Overview:__ Describe your data and present figure(s) to illustrate the response.
5. __Data Analysis and Results:__ Describe your statistical methods and interpret your results.

6 __Discussion:__ Provide a written discussion about the take-away points from your study. (You can skip the statistical jargon in this section). Also feel free to include commentary about any lessons you learned through this process.